# Generated by Django 3.0.7 on 2020-06-24 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0002_auto_20200624_0907'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='ammount',
            new_name='amount',
        ),
    ]
